import { WORLD, newGame, applyAction, tick, inputAction, difficultyForScore } from './game-logic.js';
const canvas = document.querySelector('#game'); const ctx = canvas.getContext('2d'); const scoreEl = document.querySelector('#score'); const bestEl = document.querySelector('#best'); const panel = document.querySelector('#panel'); const title = document.querySelector('#panel-title'); const copy = document.querySelector('#panel-copy'); const action = document.querySelector('#action'); const bestKey = 'flappy-asim-best';
function readBest() { try { return Number(localStorage.getItem(bestKey)) || 0; } catch { return 0; } }
function saveBest(value) { try { localStorage.setItem(bestKey, String(value)); } catch { /* persistence is optional */ } }
let state = newGame(readBest()); let last = performance.now(); let sound;
function beep(frequency, duration = .06) { try { sound ??= new AudioContext(); const osc = sound.createOscillator(); const gain = sound.createGain(); osc.frequency.value = frequency; gain.gain.setValueAtTime(.035, sound.currentTime); gain.gain.exponentialRampToValueAtTime(.001, sound.currentTime + duration); osc.connect(gain).connect(sound.destination); osc.start(); osc.stop(sound.currentTime + duration); } catch { /* sound is optional */ } }
function reset() { state = applyAction(state, 'restart'); panel.hidden = false; title.textContent = 'flappy-asim'; copy.innerHTML = 'Tap, click, or press <strong>↑</strong> to fly'; action.textContent = 'Start flying'; }
function doAction(kind) { state = applyAction(state, kind); if (kind === 'restart' || kind === 'title') { panel.hidden = false; title.textContent = 'flappy-asim'; copy.innerHTML = 'Tap, click, or press <strong>↑</strong> to fly'; action.textContent = 'Start flying'; return; } if (kind === 'flap') { panel.hidden = true; beep(580); } }
function handleInput(code) { const actionName = inputAction(code, state.phase); if (actionName) { doAction(actionName); return true; } return false; }
window.addEventListener('keydown', (event) => { if (handleInput(event.code)) event.preventDefault(); }); canvas.addEventListener('pointerdown', () => { if (state.phase === 'gameover') doAction('restart'); else doAction('flap'); }); action.addEventListener('click', () => doAction(state.phase === 'gameover' ? 'restart' : 'flap'));
function drawBackground() { const sky = ctx.createLinearGradient(0, 0, 0, WORLD.height); sky.addColorStop(0, '#72d7e8'); sky.addColorStop(.7, '#c3eff0'); sky.addColorStop(1, '#e7f5d2'); ctx.fillStyle = sky; ctx.fillRect(0, 0, WORLD.width, WORLD.height); ctx.fillStyle = '#ffffff55'; for (let i = 0; i < 4; i++) { const x = ((i * 179 - state.elapsed * 10) % 610) - 100; const y = 120 + i * 80; ctx.beginPath(); ctx.ellipse(x, y, 52, 13, 0, 0, Math.PI * 2); ctx.ellipse(x + 35, y + 3, 39, 11, 0, 0, Math.PI * 2); ctx.fill(); } }
function drawPipe(pipe) { const cap = 9; const x = Math.round(pipe.x); const topEnd = pipe.gapTop; const bottomStart = pipe.gapTop + WORLD.pipeGap; const gradient = ctx.createLinearGradient(x, 0, x + WORLD.pipeWidth, 0); gradient.addColorStop(0, '#237f50'); gradient.addColorStop(.45, '#54c675'); gradient.addColorStop(1, '#176340'); ctx.fillStyle = gradient; ctx.strokeStyle = '#174b3e'; ctx.lineWidth = 3; ctx.fillRect(x, -10, WORLD.pipeWidth, topEnd + 10); ctx.strokeRect(x, -10, WORLD.pipeWidth, topEnd + 10); ctx.fillRect(x - 6, topEnd - cap, WORLD.pipeWidth + 12, cap); ctx.strokeRect(x - 6, topEnd - cap, WORLD.pipeWidth + 12, cap); ctx.fillRect(x, bottomStart, WORLD.pipeWidth, WORLD.height - WORLD.groundHeight - bottomStart); ctx.strokeRect(x, bottomStart, WORLD.pipeWidth, WORLD.height - WORLD.groundHeight - bottomStart); ctx.fillRect(x - 6, bottomStart, WORLD.pipeWidth + 12, cap); ctx.strokeRect(x - 6, bottomStart, WORLD.pipeWidth + 12, cap); }
function drawBird() { const bob = state.phase === 'ready' ? Math.sin(state.elapsed * 4) * 7 : 0; const y = state.birdY + bob; ctx.save(); ctx.translate(WORLD.birdX, y); ctx.rotate(Math.max(-.35, Math.min(1.1, state.velocity / 650))); ctx.fillStyle = '#ffd45e'; ctx.strokeStyle = '#76542c'; ctx.lineWidth = 3; ctx.beginPath(); ctx.ellipse(0, 0, 21, 16, 0, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#f6ad43'; ctx.beginPath(); ctx.ellipse(-7, 8, 12, 7, -.3, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#fff'; ctx.beginPath(); ctx.arc(10, -7, 7, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#1a2d42'; ctx.beginPath(); ctx.arc(12, -7, 3, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#ed7840'; ctx.beginPath(); ctx.moveTo(18, -1); ctx.lineTo(32, 3); ctx.lineTo(18, 7); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.restore(); }
function drawGround() { const y = WORLD.height - WORLD.groundHeight; const speed = difficultyForScore(state.score).pipeSpeed; ctx.fillStyle = '#7fc94d'; ctx.fillRect(0, y, WORLD.width, 13); ctx.fillStyle = '#d8bb69'; ctx.fillRect(0, y + 13, WORLD.width, WORLD.groundHeight - 13); ctx.fillStyle = '#c59e54'; for (let x = -30; x < WORLD.width + 50; x += 48) { ctx.fillRect(x - ((state.elapsed * speed * .25) % 48), y + 32, 25, 5); ctx.fillRect(x - 20 - ((state.elapsed * speed * .25) % 48), y + 65, 18, 5); } }
function render() { drawBackground(); state.pipes.forEach(drawPipe); drawGround(); drawBird(); scoreEl.textContent = state.score; bestEl.textContent = `BEST ${state.best}`; if (state.phase === 'gameover' && !panel.hidden) { title.textContent = 'nice flight'; copy.innerHTML = `Score <strong>${state.score}</strong> · Best <strong>${state.best}</strong>`; action.textContent = 'Try again'; } }
function loop(now) { const dt = Math.min((now - last) / 1000, .035); last = now; const before = state.phase; state = tick(state, dt); canvas.dataset.phase = state.phase; if (before === 'playing' && state.phase === 'gameover') { saveBest(state.best); panel.hidden = false; beep(170, .13); } render(); requestAnimationFrame(loop); } window.__flappyAsim = { getState: () => ({ ...state, pipes: state.pipes.map((pipe) => ({ ...pipe })) }) }; requestAnimationFrame(loop);
